# Generated by Django 3.2.4 on 2023-09-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='nombre', max_length=45)),
                ('ApellidoP', models.CharField(db_column='ApellidoP', default='apellidop', max_length=45)),
                ('ApellidoM', models.CharField(db_column='ApellidoM', default='apellidom', max_length=45)),
                ('Fecha_nacimiento', models.DateField(db_column='Fecha_nacimiento', default='2000/01/01')),
                ('Telefono', models.IntegerField(db_column='Telefono', default=0)),
                ('Correo', models.CharField(db_column='Correo', default='algo@algo.algo', max_length=50)),
                ('Contrasena', models.CharField(db_column='Contrasena', default='contra123', max_length=64)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='alumno_has_genero',
            fields=[
                ('idalumno_has_genero', models.AutoField(db_column='idalumno_has_genero', default=1, primary_key=True, serialize=False)),
                ('fk_alumno', models.ForeignKey(db_column='fk_alumno', on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
