# Generated by Django 3.2.4 on 2023-09-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lista_tareas_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas_has_tareas',
            fields=[
                ('idListas_has_tareas', models.AutoField(db_column='idListas_has_tareas', default=1, primary_key=True, serialize=False)),
                ('fk_Lista', models.ForeignKey(db_column='fk_Lista', on_delete=django.db.models.deletion.CASCADE, to='api.lista_tareas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Listas_has_tareas',
            },
        ),
    ]
