# Generated by Django 3.2.4 on 2023-09-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alumno_as_genero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alumno_as_genero',
            new_name='alumno_has_genero',
        ),
        migrations.AlterModelTable(
            name='alumno_has_genero',
            table='alumno_has_genero',
        ),
    ]
