# Generated by Django 3.2.4 on 2023-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listas_has_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('idEtiqueta', models.AutoField(db_column='idEtiqueta', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=20)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
    ]
