# Generated by Django 3.2.4 on 2023-09-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas_has_etiquetas',
            fields=[
                ('idTareas_has_etiquetas', models.AutoField(db_column='idTareas_has_etiquetas', default=1, primary_key=True, serialize=False)),
                ('fk_Etiqueta', models.ForeignKey(db_column='fk_Etiqueta', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Tareas_has_etiquetas',
            },
        ),
    ]
