# Generated by Django 3.2.4 on 2023-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tareas_has_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Correo',
            field=models.EmailField(db_column='Correo', default='algo@algo.algo', max_length=50),
        ),
    ]
