# Generated by Django 3.2.4 on 2023-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230919_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='cocteles',
            fields=[
                ('idCoctel', models.IntegerField(db_column='idCoctel', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('imagen', models.CharField(db_column='imagen', max_length=250)),
            ],
            options={
                'db_table': 'cocteles',
            },
        ),
    ]
