# Generated by Django 3.2.4 on 2023-09-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cocteles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientes',
            fields=[
                ('idIngrediente', models.IntegerField(db_column='idIngrediente', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=500)),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
    ]
