# Generated by Django 3.2.4 on 2023-09-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ingredientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='recetas',
            fields=[
                ('idReceta', models.IntegerField(db_column='idReceta', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=10)),
                ('instrucciones', models.CharField(db_column='Instrucciones', max_length=200)),
                ('fk_idCoctel', models.ForeignKey(db_column='fk_idCocteles', on_delete=django.db.models.deletion.CASCADE, to='api.cocteles')),
                ('fk_idIngrediente', models.ForeignKey(db_column='fk_idIngredientes', on_delete=django.db.models.deletion.CASCADE, to='api.ingredientes')),
            ],
        ),
    ]
