# Generated by Django 3.2.4 on 2023-09-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recetas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recetas',
            table='recetas',
        ),
    ]
