# Generated by Django 3.2.4 on 2023-09-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_recetas_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='fk_idCoctel',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='fk_idIngrediente',
        ),
        migrations.DeleteModel(
            name='cocteles',
        ),
        migrations.DeleteModel(
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='recetas',
        ),
    ]
