# Generated by Django 3.2.4 on 2023-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230920_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('ApellidoP', models.CharField(db_column='ApellidoP', max_length=45)),
                ('ApellidoM', models.CharField(db_column='ApellidoM', max_length=45)),
                ('Telefono', models.IntegerField(db_column='Telefono', max_length=10)),
                ('Correo', models.CharField(db_column='Correo', max_length=50)),
                ('Contrasena', models.CharField(db_column='Contrasena', max_length=64)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
