# Generated by Django 3.2.4 on 2023-09-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Telefono',
            field=models.IntegerField(db_column='Telefono'),
        ),
    ]
