# Generated by Django 3.2.4 on 2023-09-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Contrasena',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='Telefono',
        ),
    ]
