# Generated by Django 3.2.4 on 2023-09-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230920_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Fecha_nacimiento',
            field=models.DateField(db_column='Fecha_nacimiento', default='01/01/1900'),
        ),
    ]
