# Generated by Django 3.2.4 on 2023-09-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230920_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuario',
            field=models.AutoField(db_column='idUsuario', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.AutoField(db_column='idTarea', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', default='Titulo', max_length=50)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('Fecha_creacion', models.DateField(db_column='Fecha_creacion', default='1900/01/01')),
                ('Fecha_vencimiento', models.DateField(db_column='Fecha_vencimiento', default='1900/01/01')),
                ('Status', models.CharField(db_column='Status', default='Pendiente', max_length=15)),
                ('Prioridad', models.CharField(db_column='Prioridad', default='Baja', max_length=10)),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'Tareas',
            },
        ),
    ]
