# Generated by Django 3.2.4 on 2023-09-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230921_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_tareas',
            fields=[
                ('idLista', models.AutoField(db_column='idLista', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=45)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
            options={
                'db_table': 'Lista_tareas',
            },
        ),
    ]
