# Generated by Django 3.2.4 on 2023-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lista_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Fecha_creacion',
            field=models.DateField(db_column='Fecha_creacion', default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='Fecha_vencimiento',
            field=models.DateField(db_column='Fecha_vencimiento', default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Fecha_nacimiento',
            field=models.DateField(db_column='Fecha_nacimiento', default='1900-01-01'),
        ),
    ]
