# Generated by Django 3.2.4 on 2023-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230923_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Fecha_nacimiento',
            field=models.DateField(db_column='Fecha_nacimiento', default='1900/01/01'),
        ),
    ]
