# Generated by Django 3.2.4 on 2023-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Fecha_nacimiento',
            field=models.DateField(db_column='Fecha_nacimiento', default='2000/01/01'),
        ),
    ]
