# Generated by Django 3.2.4 on 2023-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Fecha_creacion',
            field=models.DateField(db_column='Fecha_creacion', default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='Fecha_vencimiento',
            field=models.DateField(db_column='Fecha_vencimiento', default='2000-01-01'),
        ),
    ]
