# Generated by Django 3.2.4 on 2023-09-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230923_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='fk_Usuario',
        ),
        migrations.DeleteModel(
            name='Lista_tareas',
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
