# Generated by Django 3.2.4 on 2023-09-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Fecha_nacimiento',
        ),
    ]
